version: '3.8'

services:
  laravel:
    image: php:8.2-fpm-alpine
    container_name: laravel-app
    ports:
      - "8000:8000" 
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    command: sh -c "
      apk add --no-cache sqlite &&
      touch database/database.sqlite &&
      chmod 777 database/database.sqlite &&
      php artisan serve --host=0.0.0.0 --port=8000
      "